apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-demo
  template:
    metadata:
      labels:
        app: ci-demo
    spec:
      containers:
        - name: ci-demo
          image: bisrat1/ci-cd-demo:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV

            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WELCOME_MESSAGE

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
